# Copyright 2021 JD.com, Inc., JD AI
"""
@author: Yehao Li
@contact: yehaoli.sysu@gmail.com
"""

from .config import CfgNode as CN

_K = CN()

kfg = _K

_K.IDS = 'IDS'

_K.B_IDS = 'B_IDS'

_K.IMG_META = 'IMG_META'

########################################## TOKENS ##########################################
_K.U_TOKENS_IDS = 'U_TOKENS_IDS'

_K.U_TOKENS_IDS_WO_MASK = 'U_TOKENS_IDS_WO_MASK'

_K.G_TOKENS_IDS = 'G_TOKENS_IDS'

_K.G_TOKENS_CAP_IDS = 'G_TOKENS_CAP_IDS'     #wlx

_K.G_TOKENS_BBOX_IDS = 'G_TOKENS_BBOX_IDS'     #wlx

_K.IMG_INPUT = 'IMG_INPUT'

_K.RELATION = 'RELATION'

_K.ATTRIBUTE = 'ATTRIBUTE'

_K.U_TOKENS_TYPE = 'U_TOKENS_TYPE'

_K.G_TOKENS_TYPE = 'G_TOKENS_TYPE'

_K.G_TOKENS_CAP_TYPE = 'G_TOKENS_CAP_TYPE'    #wlx

_K.G_TOKENS_BBOX_TYPE = 'G_TOKENS_BBOX_TYPE'    #wlx

_K.U_TOKEN_EMBED = 'U_TOKEN_EMBED'

_K.G_TOKEN_EMBED_CAP = 'G_TOKEN_EMBED_CAP'

_K.G_TOKEN_EMBED_BBOX = 'G_TOKEN_EMBED_BBOX'

########################################## MASKS ##########################################

_K.TOKENS_MASKS_CAP = 'TOKENS_MASKS_CAP'

_K.TOKENS_MASKS_BBOX = 'TOKENS_MASKS_BBOX'

_K.EXT_U_TOKENS_MASKS = 'EXT_U_TOKENS_MASKS'

_K.EXT_G_TOKENS_MASKS = 'EXT_G_TOKENS_MASKS'

########################################## TARGET ##########################################
_K.U_TARGET_IDS = 'U_TARGET_IDS'

_K.G_TARGET_IDS = 'G_TARGET_IDS'

_K.G_TARGET_COUNT_IDS = 'G_TARGET_COUNT_IDS'    #wlx

_K.G_TARGET_CAP_IDS = 'G_TARGET_CAP_IDS'    #wlx

_K.G_TARGET_PMP = 'G_TARGET_PMP'    #wlx

_K.G_TARGET_BBOX_IDS = 'G_TARGET_BBOX_IDS'    #wlx

_K.V_TARGET = 'V_TARGET'

_K.V_TARGET_LABELS = 'V_TARGET_LABELS'

_K.ITM_NEG_LABEL = 'ITM_NEG_LABEL'

########################################## FEATS ##########################################
_K.MP_FEATS = 'MP_FEATS'

_K.MP_RESULTS = 'MP_RESULTS'

_K.PC_RESULTS = 'PC_RESULTS'

_K.PMP_RESULTS = 'PMP_RESULTS'

_K.PMP_FEATS = 'PMP_FEATS'

_K.PMP_BOX_FEATS = 'PMP_BOX_FEATS'

_K.PMP_GB_FEATS = 'PMP_GB_FEATS'

_K.BBOX_RESULTS = 'BBOX_RESULTS'

_K.CLS_SCORE = 'CLS_SCORE'

_K.CENTERNESS = 'CENTERNESS'

_K.ATT_FEATS = 'ATT_FEATS'

_K.ATT_FEATS_WO_MASK = 'ATT_FEATS_WO_MASK'

_K.ATT_MASKS = 'ATT_MASKS'

_K.PMP_MASKS = 'PMP_MASKS'

_K.EXT_ATT_MASKS = 'EXT_ATT_MASKS'

_K.ATT_FEATS_LOC = 'ATT_FEATS_LOC'

_K.P_ATT_FEATS = 'P_ATT_FEATS'

_K.P_ATT_FEATS_BBOX = 'P_ATT_FEATS_BBOX'

_K.GLOBAL_FEATS = 'GLOBAL_FEATS'

_K.PMP_GLOBAL_FEATS = 'PMP_GLOBAL_FEATS'

########################################## STATES ##########################################
_K.U_HIDDEN_STATES = 'U_HIDDEN_STATES'

_K.G_HIDDEN_STATES = 'G_HIDDEN_STATES'

_K.G_HIDDEN_STATES_BBOX = 'G_HIDDEN_STATES_BBOX'

_K.HISTORY_STATES = 'HISTORY_STATES'

_K.ENC_HISTORY_STATES = 'ENC_HISTORY_STATES'

_K.U_CELL_STATES = 'U_CELL_STATES'

_K.G_CELL_STATES = 'G_CELL_STATES'

_K.G_CELL_STATES_BBOX = 'G_CELL_STATES_BBOX'

########################################## LOGITS ##########################################
_K.U_LOGITS = 'U_LOGITS'

_K.G_LOGITS_CAP = 'G_LOGITS_CAP'

_K.G_LOGITS_BBOX = 'G_LOGITS_BBOX'

_K.V_LOGITS = 'V_LOGITS'

_K.V_REGRESS = 'V_REGRESS'

_K.ITM_LOGITS = 'ITM_LOGITS'

########################################## Others ##########################################
_K.IMG_H = 'IMG_H'

_K.IMG_W = 'IMG_W'

_K.SEQ_PER_SAMPLE = 'SEQ_PER_SAMPLE'

_K.REG_PER_SAMPLE = 'REG_PER_SAMPLE'

_K.G_LOCTION = 'G_LOCTION'

_K.SAMPLE_PER_SAMPLE = 'SAMPLE_PER_SAMPLE'

_K.G_SENTS_IDS = 'G_SENTS_IDS'

_K.G_BBOX_IDS = 'G_BBOX_IDS'

_K.G_LOGP = 'G_LOGP'

_K.G_LOGP_BBOX = 'G_LOGP_BBOX'

_K.OUTPUT = 'OUTPUT'

_K.BBOX_OUTPUT = 'BBOX_OUTPUT'

_K.MP_NUM_OUTPUT = 'MP_NUM_OUTPUT'

_K.DECODE_BY_SAMPLE = 'DECODE_BY_SAMPLE'

_K.REWARDS = 'REWARDS'

_K.SS_PROB = 'SS_PROB'

_K.TIME_STEP = 'TIME_STEP'

_K.TIME_STEP_BBOX = 'TIME_STEP_BBOX'

_K.COCO_PATH = '../coco_caption'

_K.TEMP_DIR = './data/temp'

########################################## COSNet ##########################################
_K.SEMANTICS_IDS = 'SEMANTICS_IDS'

_K.SEMANTICS_MASK = 'SEMANTICS_MASK'

_K.EXT_SEMANTICS_MASKS = 'EXT_SEMANTICS_MASKS'

_K.SEMANTICS_LABELS = 'SEMANTICS_LABELS'

_K.SEMANTICS_MISS_LABELS = 'SEMANTICS_MISS_LABELS'

_K.SEMANTICS_PRED = 'SEMANTICS_PRED'

_K.SEMANTICS_FEATS = 'SEMANTICS_FEATS'

_K.SEMANTICS_POS_PRED = 'SEMANTICS_POS_PRED'