OUTPUT_DIR : "work_dirs/jmdc_V1"
DATASETS:
  TRAIN: 'MRC_CrowdCaption_MP'
  VAL: 'MRC_CrowdCaption_MP'
  TEST: 'MRC_CrowdCaption_MP'
###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 16
  NUM_WORKERS: 2
  INPUT_SIZE:  384   #224
  FEATS_FOLDER: './open_source_dataset/CrowdMultiCaptions_MRC/features_img/swin_large'
  HRNET_FOLDER: '/data1/dataset/crowdcaption/hrnet/hrnet_backbone'
  ANNO_FOLDER_TRAIN:  './open_source_dataset/CrowdMultiCaptions_MRC/JMDC8/mrc_anno_train.pkl'
#  ANNO_FOLDER_VAL:  './open_source_dataset/CrowdMultiCaptions_MRC/GIVEN_IMG/mrc_anno_val.pkl'
  ANNO_FOLDER_VAL:  './open_source_dataset/CrowdMultiCaptions_MRC/JMDC8/mrc_anno_val.pkl'
  ANNO_FOLDER_TEST:  './open_source_dataset/CrowdMultiCaptions_MRC/JMDC8/mrc_anno_test.pkl'
#  ANNO_FOLDER_TEST:  './open_source_dataset/CrowdMultiCaptions_MRC/GIVEN_IMG/mrc_anno_test.pkl'
  ANNO_FOLDER_TRAIN_ID: './open_source_dataset/CrowdMultiCaptions_MRC/JMDC8/mrc_train_ids2path.json'
  ANNO_FOLDER_VAL_ID: './open_source_dataset/CrowdMultiCaptions_MRC/JMDC8/mrc_val_ids2path.json'
  ANNO_FOLDER_TEST_ID: './open_source_dataset/CrowdMultiCaptions_MRC/JMDC8/mrc_test_ids2path.json'
  SEQ_PER_SAMPLE:  4
  REG_PER_SAMPLE:  4
  MAX_FEAT_NUM: 145

ENGINE:
  NAME: 'DefaultTrainer'
######################################### Scheduled sampling #########################################

#SCHEDULED_SAMPLING:
#  START_EPOCH: 4000         # iter
#  INC_EVERY_EPOCH: 1000
#  INC_PROB: 0.05
#  MAX_PROB: 0.3

SCHEDULED_SAMPLING:
  START_EPOCH: 2         # iter
  INC_EVERY_EPOCH: 5
  INC_PROB: 0.05
  MAX_PROB: 0.5
######################################### MODEL #########################################
MODEL:
  GIVENBGT: False
  ENCODER: 'CrowdPlusEncoder'
  ENCODER_DIM: 1024
  BBOX_PREDICTOR: 'UpDownDecoder_BBOX'
  DECODER: 'UpDownDecoder'
  DECODER_DIM: 1024
  SCALE: 256
  BACKBONE: 'SwinTransformer384_large'
  SWIN_PTH: '/data1/wlx/project/202209_xmodaler_dif_pers/data/swin_large_patch4_window12_384_22k_wlx.pth'
  VOCAB_SIZE: 2660 # include <BOS>/<EOS>
  BBOX_SIZE: 257   #257    #129 # include <BOS>/<EOS>
  PREDICTOR: 'BasePredictor'
  PREDICTOR_BBOX: 'BasePredictor_BBOX'
  PRED_DROPOUT: 0.5
  MAX_SEQ_LEN: 50
  MAX_BBOX_LEN: 6
  META_ARCHITECTURE: 'RnnAttEncoderDecoderMP'
  MULTIPERSPECTIVE_COUNT: 'MULTIPERSPECTIVE_COUNT'
  MULTIPERSPECTIVE_MAPS_PREDICTION: 'MULTIPERSPECTIVE_MAPS_PREDICTION'
  TOKEN_EMBED_BBOX:
    NAME: 'JDMCTokenBaseEmbeddingBBOX'
    DIM: 1024
    ACTIVATION: 'relu'
    USE_NORM: False
    DROPOUT: 0.5
  TOKEN_EMBED:
    NAME: 'JDMCTokenBaseEmbedding'
    DIM: 1024
    ACTIVATION: 'relu'
    USE_NORM: False
    DROPOUT: 0.5
  VISUAL_EMBED:
    NAME: 'VisualBaseEmbedding'
    IN_DIM: 1536   # swin384 large
    G_IN_DIM: 1536
    #    IN_DIM: 2048
    OUT_DIM: 1024
    ACTIVATION: 'relu'
    USE_NORM: False
    DROPOUT: 0.5
  BILINEAR:
    DIM: 1024
    HEAD: 8
    BIFEAT_EMB_ACT: 'relu'
    ACT: 'celu'
    ELU_ALPHA: 1.3
    ENCODE:
      ATT_MID_DIM: [128, 64, 128]
      ATT_MID_DROPOUT: 0.1
      DROPOUT: 0.5
      BIFEAT_EMB_DROPOUT: 0.3
      LAYERS: 4
  UPDOWN:
    ATT_EMBED_SIZE: 512
    DROPOUT1: 0.0
    DROPOUT2: 0.0
    ATT_EMBED_DROPOUT: 0.0
####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 140
  WRITE_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 3
  BASE_LR: 0.0005  #0.0005
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MOMENTUM: 0.9
  DAMPENING: 0.0
  NESTEROV: 0.0
  BETAS: [0.9, 0.98]
  EPS: 1.0e-9
  GRAD_CLIP: 0.5
  GRAD_CLIP_TYPE: 'norm'
  NORM_TYPE: 2.0
  BBOX_RATE: 1.0

####################################### lr scheduler #######################################
LR_SCHEDULER:
  NAME: 'NoamLR'
  MODEL_SIZE: 1024
  FACTOR: 1.0
  WARMUP: 1000
#  NAME: 'StepLR'
#  STEP_SIZE: 5
#  GAMMA: 0.8

####################################### losses #######################################
LOSSES:
  NAMES: ['JMDCCrossEntropy']
#  NAMES: ['CrossEntropy']
#  NAMES: ['LabelSmoothing']
#  LABELSMOOTHING: 0.1
####################################### scorer #######################################
SCORER:
  NAME: 'BaseScorer'
  TYPES: ['Cider']
  WEIGHTS: [1.0]
  GT_PATH: './open_source_dataset/CrowdMultiCaptions_MRC/JMDC8/mrc_train_gts.pkl'
  CIDER_CACHED: './open_source_dataset/CrowdMultiCaptions_MRC/JMDC8/mrc_train_cider.pkl'
  EOS_ID: 0

####################################### decode strategy #######################################
DECODE_STRATEGY:
  NAME: 'BeamSearcher'
  BEAM_SIZE: 3

####################################### evaluation #######################################
INFERENCE:
  NAME: 'RegionMPEvaler'
  VOCAB: './open_source_dataset/CrowdMultiCaptions_MRC/JMDC8/cap_vocabulary.txt'
  DETBBOX: './open_source_dataset/CrowdMultiCaptions_MRC/JMDC8/loc_vocabulary.txt'
  ID_KEY: 'image_id'
  VALUE: 'caption'
#  VAL_ANNFILE: './open_source_dataset/CrowdMultiCaptions_MRC/GIVEN_IMG/mrc_val.json'
  VAL_ANNFILE: './open_source_dataset/CrowdMultiCaptions_MRC/JMDC8/mrc_val.json'
  TEST_ANNFILE: './open_source_dataset/CrowdMultiCaptions_MRC/JMDC8/mrc_test.json'
#  TEST_ANNFILE: './open_source_dataset/CrowdMultiCaptions_MRC/GIVEN_IMG/mrc_test.json'
  GENERATION_MODE: True